name: Build and Push Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Release
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/dockpurge
          docker build -t $IMAGE_NAME:${{ env.RELEASE_VERSION }} -t $IMAGE_NAME:latest .

      - name: Push
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/dockpurge
          docker push $IMAGE_NAME:${{ env.RELEASE_VERSION }}
          docker push $IMAGE_NAME:latest

      - name: Link
        run: echo "Imagem disponível em https://github.com/orgs/${{ github.repository_owner }}/packages/container/package/dockpurge"
